import { Metadata } from 'next';
import { NextIntlClientProvider, useTranslations } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import "@/app/globals.css";

import localFont from 'next/font/local';

const hankenGrotesk = localFont({
  src: [
    {
      path: './fonts/HankenGrotesk-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/HankenGrotesk-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/HankenGrotesk-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/HankenGrotesk-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-hanken-grotesk',
});

const silkscreen = localFont({
  src: './fonts/Silkscreen-Regular.ttf',
  variable: '--font-silkscreen',
});

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${silkscreen.variable} ${hankenGrotesk.variable}`}>
      <body className="px-[32px] py-[64px] flex justify-center font-para text-fg light-mode">
        <NextIntlClientProvider messages={messages}>
          <main className="w-full h-full flex flex-col justify-center items-center max-w-[512px] gap-4 font-normal">
            {children}
          </main>
          <WithLove />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

function WithLove() {
  const translationsCommon = useTranslations('common');

  return (
    <div className="text-fg absolute left-0 right-0 bottom-0 h-16 flex flex-col items-center justify-center text-xs">
      <span>{translationsCommon('credits_by')}</span>
      <span>{translationsCommon('credits_for')}</span>
    </div>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
